= Rollup Plugin Node Mock Server
:toc:

image:https://travis-ci.org/dschulten/rollup-plugin-node-mock-server.svg?branch=master["Build Status", link="https://travis-ci.org/dschulten/rollup-plugin-node-mock-server"]

Rollup plugin to run the https://github.com/smollweide/node-mock-server[node-mock-server] in a rollup project.

The node-mock-server serves both the static resources of your project and features a file-based api mock with a middleware hook for dynamic responses. The server comes with a UI where developers can conveniently edit resources and choose which success or error response the API should return at runtime.

You can also import your mock api from a https://swagger.io/specification/[Swagger (OpenAPI)] specification.


== Installation
    npm i -D rollup-plugin-node-mock-server

== Usage
The _test_  folder contains a sample mock definition in _mock/index.js_.

Create a _mock_ folder in your project and copy the contents of the _test/mock_ folder into it. The file https://github.com/dschulten/rollup-plugin-node-mock-server/blob/master/test/mock/index.js[_test/mock/index.js_] contains a sample definition for your mock server. For an explanation of the options see https://github.com/smollweide/node-mock-server/blob/master/doc/readme-options.md[node-mock-server options]. Furthermore consider the comprehensive documentation in the https://github.com/smollweide/node-mock-server[node-mock-server readme].

Basic configuration of the plugin:

.rollup.config.js
[source,javascript]
----
import nodeMockServer from 'rollup-plugin-node-mock-server'

export default {
    entry: 'index.js',
    dest: './dist/bundle.js',
    format: 'iife',
    plugins: [
        nodeMockServer(),
    ]
}
----

Combine with https://github.com/thgh/rollup-plugin-livereload[rollup-plugin-livereload]:

[source,javascript]
----
import livereload from 'rollup-plugin-livereload'
import nodeMockServer from 'rollup-plugin-node-mock-server'

export default {
    entry: 'index.js',
    dest: './dist/bundle.js',
    format: 'iife',
  plugins: [
    nodeMockServer(),
    livereload()
  ]
}
----
When you execute your rollup pipeline with the node-mock-server definition above, the server will start serving at _/_ from the _/public_ and _/dist_ folder and it automatically opens the browser with _public/index.html_ and the API mock UI.

All of these paths can be reconfigured in _mock/index.js_, see the https://github.com/smollweide/node-mock-server/blob/master/doc/readme-options.md[options] `uiPath` and `expressMiddleware`.

== Options
Below you see the available plugin options and their default values. They only affect the behaviour of the rollup-plugin, not the mock behaviour.

[source,javascript]
----
nodeMockServer({
    // project folder containing the mock data
    dirName: 'mock',
    // launch index.html page and mock ui in browser
    shouldOpenOnStart: true,
    // allows to adjust the index.html url,
    // e.g. to pass parameters to the index page
    url: 'localhost:3001/'}
});
----
Use the _index.js_ file inside your _mock_ folder to configure the actual https://github.com/smollweide/node-mock-server/blob/master/doc/readme-options.md[node-mock-server options].

== Building the Project
    npm run build

== Testing the Project
Change into the _test_ directory. Then:

    npm install
    npm start

== Debugging rollup-plugin-node-mock-server
When you start hacking on the plugin, you may want to debug it. From working directory _/test_ run _node_modules/rollup/bin/rollup_ with application parameter `-c` in your IDE and set breakpoints in _test/node_modules/rollup-plugin-node-mock-server/dist/index.cjs.js_.

== License
The MIT License (MIT). Please see link:LICENSE[License File] for more information.
